#############################################################################
# Makefile for building: Project
# Generated by qmake (2.01a) (Qt 4.8.5) on: mar sep 17 00:43:52 2013
# Project:  ../Project-2/Project.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/lib64/qt4/mkspecs/linux-g++ -o Makefile ../Project-2/Project.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++ -I../Project-2 -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I../Project-2 -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-z,relro
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Project-2/main.cpp \
		../Project-2/mainwindow.cpp \
		../Project-2/TDAFile.cpp \
		../Project-2/Campo.cpp \
		../Project-2/TDARecordFile.cpp \
		../Project-2/Header.cpp \
		../Project-2/Index.cpp \
		../Project-2/Registro.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		TDAFile.o \
		Campo.o \
		TDARecordFile.o \
		Header.o \
		Index.o \
		Registro.o \
		moc_mainwindow.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		../Project-2/Project.pro
QMAKE_TARGET  = Project
DESTDIR       = 
TARGET        = Project

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../Project-2/Project.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -spec /usr/lib64/qt4/mkspecs/linux-g++ -o Makefile ../Project-2/Project.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/shared.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/lib64/qt4/mkspecs/linux-g++ -o Makefile ../Project-2/Project.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Project1.0.0 || $(MKDIR) .tmp/Project1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Project1.0.0/ && $(COPY_FILE) --parents ../Project-2/mainwindow.h ../Project-2/TDARecordFile.h ../Project-2/TDAFile.h ../Project-2/Campo.h ../Project-2/Header.h ../Project-2/Index.h ../Project-2/Registro.h .tmp/Project1.0.0/ && $(COPY_FILE) --parents ../Project-2/main.cpp ../Project-2/mainwindow.cpp ../Project-2/TDAFile.cpp ../Project-2/Campo.cpp ../Project-2/TDARecordFile.cpp ../Project-2/Header.cpp ../Project-2/Index.cpp ../Project-2/Registro.cpp .tmp/Project1.0.0/ && (cd `dirname .tmp/Project1.0.0` && $(TAR) Project1.0.0.tar Project1.0.0 && $(COMPRESS) Project1.0.0.tar) && $(MOVE) `dirname .tmp/Project1.0.0`/Project1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Project1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../Project-2/Campo.h \
		../Project-2/Header.h \
		../Project-2/TDAFile.h \
		../Project-2/TDARecordFile.h \
		../Project-2/Registro.h \
		../Project-2/Index.h \
		../Project-2/mainwindow.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) ../Project-2/mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: ../Project-2/main.cpp ../Project-2/mainwindow.h \
		../Project-2/Campo.h \
		../Project-2/Header.h \
		../Project-2/TDAFile.h \
		../Project-2/TDARecordFile.h \
		../Project-2/Registro.h \
		../Project-2/Index.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Project-2/main.cpp

mainwindow.o: ../Project-2/mainwindow.cpp ../Project-2/mainwindow.h \
		../Project-2/Campo.h \
		../Project-2/Header.h \
		../Project-2/TDAFile.h \
		../Project-2/TDARecordFile.h \
		../Project-2/Registro.h \
		../Project-2/Index.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../Project-2/mainwindow.cpp

TDAFile.o: ../Project-2/TDAFile.cpp ../Project-2/TDAFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDAFile.o ../Project-2/TDAFile.cpp

Campo.o: ../Project-2/Campo.cpp ../Project-2/Campo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Campo.o ../Project-2/Campo.cpp

TDARecordFile.o: ../Project-2/TDARecordFile.cpp ../Project-2/TDARecordFile.h \
		../Project-2/Campo.h \
		../Project-2/TDAFile.h \
		../Project-2/Registro.h \
		../Project-2/Index.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDARecordFile.o ../Project-2/TDARecordFile.cpp

Header.o: ../Project-2/Header.cpp ../Project-2/Header.h \
		../Project-2/TDAFile.h \
		../Project-2/Campo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Header.o ../Project-2/Header.cpp

Index.o: ../Project-2/Index.cpp ../Project-2/Index.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Index.o ../Project-2/Index.cpp

Registro.o: ../Project-2/Registro.cpp ../Project-2/Registro.h \
		../Project-2/Campo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Registro.o ../Project-2/Registro.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

